name: macos

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  perl:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Perl
      run: brew install perl
    - run: env
    - run: perl -V

    - name: Install deps
      run: >
        curl -L https://cpanmin.us >cpanm && chmod +x cpanm

        ./cpanm --quiet --notest
        Test::More YAML::PP
    - name: Run Tests
      run: |
        perl Makefile.PL
        make
        prove -br t
